export default {
  results: [
    {
      name: "Results #1",
      slug: "result-1",
      score: 0.17813765182186234,
      fileOneName: "001.java",
      fileTwoName: "001-p.java",
      fileOneMatches: [2, 3, 4, 5, 6, 7],
      fileTwoMatches: [
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        61,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69,
        70,
        71,
        72,
        73,
        74,
        75,
        76,
        77,
        78,
        79,
        80,
        81,
        82,
        83,
        84,
        85,
        86,
        87,
        88,
        89,
        90,
        91,
        92,
        93,
        94,
        95,
        96,
        97
      ],
      fileOneLines: [
        "public class ERCJb {",
        "private q1INlWzHq i(lbL4 h8xdE8h9, qxnOLy6W U, pTf5EDo phA, Q WkUxk_gEu) {",
        "for (NdQ = cp0Dmy + A * UTck * IG2; oao_w1Ri * kS_b8MoFn < M * W9SnB5P; O4 = SyARKYrM < Fncov) {",
        "if (bTJy0GPO * rAFiA > l1yTboN) {",
        "JSYRvvDwK I = jnb + _Q < iOSn();",
        "wlJ VDL0 = MeAO9qK < oO + A8M * czWof5AfJ;",
        "Z6I2 = MB > A(iK9Qd);}",
        "m = eZ;",
        "if (XFnhUkIC(g + L8W8ck, _nr7mOr + yw8DE, ESh + YRnojwjN)) {",
        "fo_Us q = PoexXgeL < D * OcRs0o(Xbic2bFGx, z, j9RH);",
        "a1 _Z5 = tQfOEH > az > _AbRQq < CVivz;}",
        "else {",
        "qFz2 UiyktDcUR = vqglV * F + PH(Hv, Opx7S3DN2, y3zBVn);",
        "fz5o = BF + ofE5wtFUN + T0VU;",
        "nR GxTIp2 = YWLMLJ(MUc * uLtaUK);",
        "u1p4YoJK = hQq < uC * R1yr8NFR(pMwVy8, WghqEbhH6, UlNPXDhz);",
        "Td1S a = TsBKg86 * J < QMt();",
        "F = J > vC > uxjyEbTtI > SKlD;}",
        "for (YeY4X_G VkfM = UWEg > x * F; q0ZscHCj; mYCi = UID6e0SH3 + W6v > z + EqHDcbLhY) {",
        "S sIoltBh = EB2w();",
        "XbfBez4X co6KJ = BhJgi5zK;}",
        "for (Zp jLJA = Zk7 > R4Q0tK4xE; S6GCb0Zt2; AbyCT = Su < qnhsAYN + r) {",
        "LDauk = h > cWQw7xjb < jgBEifa1(vfsnsL0jz);",
        "wA s = lJRD;",
        "Q46Q2OT = nVmH2uep(JsA * uB5X);",
        "GcUg1kza FJOw = KgAsR(QfIqw6CZ, IufRGU, ic) + jBGqJa9 > h8DiH;}}",
        "K1Q0 = _(bubC > TYSmec);",
        "taqhLQ4j = e6KAzQ9x < hBBX < eo + Y;",
        "haazvSXo = D3S > QDlK * nMC;}}"
      ],
      fileTwoLines: [
        "public ",
        "class	",
        "	",
        "",
        "	  n5o8Cm 	",
        "   	 {    ",
        "",
        "public  ",
        "	 WORxeS ",
        "	",
        "   ",
        "oy66(sJwrFiaIv",
        "	   VG,	   ",
        "	QjB  	 W,	   ",
        " ",
        "pi5CvZA   	 wNpm898r,	 ",
        "T 	",
        " ",
        "		t)  { ",
        "  m8tx",
        "",
        " 	 	 d6",
        " ",
        "",
        "  =   ",
        "",
        "		 	iKK()",
        "	",
        " ",
        "	  * ",
        " 	",
        "  ",
        " W 			 > ",
        "  ",
        "",
        " 	plMX; ",
        " ",
        "",
        "McQU7TR3W	",
        " ",
        "   	= 	",
        " ",
        "	  bTAnqjmmF(B",
        "  	 	<		   ",
        "emcSCDaLQ); 	  	 muCjL_p5 	",
        " =   ",
        "",
        "wyEI",
        "  * 			 F8DKhTnn 	 ",
        "	 * 	   		",
        "",
        "eiCgR6dxi ",
        "	",
        "	",
        "+		 ",
        "",
        "FDToYUv4;    	 	",
        "while ",
        "",
        "		 ",
        " (BRiIC",
        "			 ",
        "*	   	 ",
        "",
        "",
        "vw > 		  	  VR6dWlL_  	 ",
        "",
        " ",
        "	 * 	 Cs)	",
        " 	",
        "",
        "	    {  ",
        "",
        "wKeK	   ",
        "=	",
        "  	 	 WC    +     ",
        "",
        "_f40ZK0eg ",
        " ",
        "	 	>		    	TQFLL6;  	  	if	   ",
        " (TypBPJ",
        " 		 <",
        "	",
        "",
        " 	Yz 	 	 *	",
        "	  a1gDu)	  	   {",
        "",
        " ",
        " X5SYj ",
        "  ",
        " ",
        " Z1",
        "",
        " 	   =     a()",
        "  ",
        "			  ",
        " >  	 ",
        " ",
        "",
        " LFJ			",
        "",
        " +",
        "   ",
        "",
        "  Hmy;",
        "	   ",
        "",
        "	 f",
        "",
        "",
        " =	",
        "",
        " 	",
        "	   Gq(Pd) ",
        "",
        " <  ",
        "  HDkAd5; 	",
        "",
        "  ",
        "		Dkt8wwA4",
        " 		   ",
        "=  	",
        " ",
        " ",
        "r18_3xq 	",
        "",
        "",
        "<	",
        " t2pW  	 + ",
        "    Y  > 			  cp2J;",
        "	   	",
        "",
        "OOaRIG",
        "     		Z0aVFtwIP 	  ",
        "",
        "	 = 	 AWiuDhW 	  ",
        " 		*",
        "    fax	 +	",
        " ",
        " 	QBxQbK	",
        " 	",
        " >",
        "",
        "	 ",
        "Z;	 ",
        "		  ",
        " tmnGenc  ",
        "  ",
        "	 osFeWO",
        "",
        " =   	n9;} 		  	  X	",
        " ",
        "	= 	 	 ",
        "  	G9HhFq;  	   if  ",
        " 	 ",
        "",
        " 	(Xwya(WoPfG",
        "  ",
        "+",
        " 	 	",
        " bK_jlq2it,  	 	  UZ  	+",
        "",
        "		",
        " 	vg4XWH, ",
        " ROsQ3N 	 	 	+    	 ",
        "g)) 	",
        " 		{	  ",
        " 	",
        "MnApw_",
        "  ",
        "	  lX90 ",
        "		 	=",
        "",
        "  	  bgy",
        "		",
        "  ",
        ">    DR",
        "	    <",
        " ",
        " 		",
        "  	QlnYHc4pf",
        "  <	  	",
        "dCIbrBtR;",
        "     ",
        "SrWYFw",
        "",
        " 		",
        "	=     tx1RKw(qVRYPb	 	  ",
        "",
        "",
        "<	",
        "	 ",
        "  Iz39,    	 Jf2bQw   ",
        "  ",
        "< 	 		 gDD,		  bdBsWgx",
        "   ",
        " <     ",
        "",
        "",
        "		xmdpV969);	",
        " ",
        "",
        "	dxZQ7	  L2GSVmBd   	 ",
        " =    ",
        " YeqrX(A,   ",
        "	 ",
        "	",
        "VCjK, 	  	  qT8wqplWn) 	",
        " *  		 ",
        " ",
        "mNIeeK9   	>",
        " 		unHdQ9;}   ",
        "",
        "	 else	",
        "",
        "",
        " {",
        "    ",
        "",
        "BN4k 		   LPElf	",
        "",
        " ",
        " =    wX(PUohSD,",
        " ",
        " 	Zj,		 	dMg)	 	   	+",
        " ",
        "		 XuMa4dt3  ",
        "*",
        "",
        " ",
        " Q;   	",
        "  cB",
        "  ",
        "	 ",
        "Wkfyz",
        "     		=   ",
        " CoJbsir21(wI2t	 ",
        " 	 	*	",
        "	",
        " pdphbm);	   	nXzi	    ",
        "",
        " = ",
        "",
        "",
        "Yq1MaI 		 	 + 	 x",
        "  	  		 + 	 	",
        "eaA1; ",
        " 	  	 qP		",
        " 	",
        "irVSh	  	 =  	   	tx0 	  >  	",
        "	",
        "",
        " 	xG5vEWp 	  	 	*  	 	 ",
        " ",
        "	LsCeX0p(x,",
        "   ",
        " ",
        "YT6KqdT);",
        "",
        "  ",
        "  L6lK",
        "",
        "	",
        "	  =  	  		",
        "nXCH(VFzJJ, ",
        "	",
        "oji, bDntPe)  		*	 ",
        "Cf ",
        " ",
        "",
        "  	 	>",
        " 			 Fx9UMF;  	  		nFn ",
        "  	",
        "",
        "		t  ",
        "	",
        "	=   ",
        "		  	lp5nsDH() ",
        "",
        "	",
        " >",
        "",
        "	  	   icX563Wu",
        " 	*  ",
        " ",
        " 			",
        "bR; vuB3C9r5y		 ",
        "= 		 	 iC6z7V ",
        " 		  < ",
        "	",
        "   ",
        "eKh",
        "  ",
        "<",
        " ",
        "",
        "mttJ",
        "	 ",
        " <			 hx;}	",
        "	",
        "    ",
        "Co5mv1U  ",
        "  y3MF",
        "",
        " 		=  ",
        " ",
        "		  ANPxP ",
        "",
        "<  A9hW_v;",
        "			 ",
        " ",
        "while 	  		(KsW2dpQZ)	",
        " ",
        " ",
        "		 {",
        "   	u2	 =  c1CDgr(wt) ",
        "			",
        "",
        ">		    Biv3wZc3	 	 < ",
        "",
        "	 ",
        "	 FN7jlU;  ",
        " 	",
        "Y ",
        "	",
        " ",
        " 	xnWt ",
        "",
        "= ",
        "  ",
        "btt; 	  KIY  	  ",
        " ZR	    ",
        " 		=	 		",
        " ",
        "pr ",
        "	  ",
        "< 		  fUL_KN3Ns",
        "",
        "  			+",
        " ",
        " ",
        "jTrYi(X, ",
        "",
        "GpL5O3, ",
        "",
        "",
        "hiVbNH); 		 VDLBVqs ",
        "",
        " ",
        "=	",
        "  		T71wiui(_SH   *	",
        "",
        " SMMz);HzW3d4Xfn 	",
        " ",
        " ",
        "= ",
        "	",
        " ",
        "		QAnfINi   + ",
        " ",
        " 		 ",
        "SE_jXG",
        " > 	 	",
        "  ",
        "	jzfG0oN; ",
        "",
        "",
        "}",
        "  	utW  	 _ ",
        "=",
        "	  ",
        "RvAm ",
        " 	 *",
        " ",
        "",
        "	 S4Tr18E 	",
        " ",
        "  	< 		 ",
        "  gug;	 ",
        "",
        " 		",
        "while   (qFq)  ",
        "	  	{",
        " 			",
        " ",
        "pVj  	 	 F	  ",
        "",
        "=     K6KHDjy	   	 *  ",
        " ",
        "",
        "wiekvQLvx		   	> 	  ",
        "",
        "	e0vr 	  ",
        "		 *	 	 	yodM1PoAB;  UqFJW  			Z",
        "    ",
        " 	= 	 		Q7IEt;	",
        "	 ukKXcHq",
        "",
        "	   RawUtdX  	 ",
        "",
        "	",
        "=",
        " ",
        "  	w0dPt();  		",
        "	 ",
        "  nT3J1VI ",
        "",
        "UlP8MiFKP	",
        "  	=  	 ",
        "X;ukjtKX    =	  tCMmrqa2O ",
        " ",
        " 	  +		  	",
        " ",
        "A",
        " 		<     Qi_Fmi9X	",
        "		 + 	 	KKn4GD;   ",
        "	}_jMDUcrR9  	",
        "	 ",
        "  =	  ",
        "Jgzp2i",
        " ",
        "   ",
        "	>",
        "",
        "",
        "  Y;",
        "  } 		 	XtNo0GfCR	",
        "	   	  =		 ",
        " 	 Gpn ",
        "   ",
        " + 		NvFDVVvE   	  >	",
        "",
        "  	 ",
        "	 XiCMBxKt   			> Bj;  ",
        " xcQ =",
        "  	 b(BrcX, ",
        "   ",
        "Wgj, ",
        "   ",
        " IMAhDkbsk)   * 	",
        "",
        "",
        "    	rsg8rZ5t9	 ",
        "	 + ",
        "		",
        " 	",
        "N6RzxF;  ZNAZPguWR		  	 ",
        "",
        " =  	   Gs9bx	",
        "	  	   * 	  XytlxeGVn	   	 <	 ",
        "",
        " 	",
        "   xGT;}}"
      ],
      matches: [
        [[3], [39]],
        [[5], [74, 75, 76]],
        [[6], [85]],
        [[4], [66]],
        [[3], [57]],
        [
          [5, 6],
          [81, 82, 83, 84, 85]
        ],
        [[2], [27, 28, 29, 30]],
        [[5], [78]],
        [[2], [33]],
        [[6], [85, 86]],
        [[5], [61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74]],
        [[4], [61, 62, 63, 64, 65, 66]],
        [[2], [27]],
        [[5], [80]],
        [[3], [45]],
        [
          [4, 5],
          [66, 67, 68, 69]
        ],
        [[3], [48, 49, 50, 51, 52, 53, 54, 55]],
        [[6], [81, 82, 83, 84, 85, 86]],
        [[7], [94, 95, 96, 97]],
        [[5], [74, 75, 76, 77, 78, 79, 80]],
        [[6, 7], [94]],
        [
          [3],
          [
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44,
            45
          ]
        ],
        [[3], [39, 40, 41, 42, 43, 44, 45]],
        [[5], [76, 77, 78, 79, 80]],
        [
          [3],
          [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]
        ],
        [[3], [46, 47, 48]],
        [[3], [48, 49, 50]],
        [[3], [49]],
        [[2], [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]],
        [[2], [22, 23, 24, 25, 26, 27]],
        [[5], [76]],
        [[3], [48]],
        [[3], [48, 49]],
        [[7], [94]],
        [
          [3, 4],
          [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58]
        ],
        [[6], [92, 93, 94]],
        [[6], [81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92]],
        [[4], [58, 59, 60, 61, 62, 63]]
      ]
    },
    {
      name: "Results #2",
      slug: "result-2",
      score: 0.154475703324808,
      fileOneName: "002.java",
      fileTwoName: "002-p.java",
      fileOneMatches: [
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31
      ],
      fileTwoMatches: [
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69,
        70,
        71,
        72,
        73,
        74,
        75,
        76,
        77,
        78,
        79,
        80,
        81,
        82,
        83,
        84,
        85,
        86,
        87,
        88,
        89,
        90,
        91,
        92,
        93,
        94,
        95,
        96,
        97,
        98,
        99,
        100,
        101,
        102,
        103,
        104,
        105,
        106,
        107,
        108,
        109,
        110,
        111,
        112,
        113,
        114,
        115,
        116,
        117,
        118,
        119,
        120,
        121,
        122,
        123,
        124,
        125,
        126,
        127,
        128,
        129,
        130,
        131,
        132,
        133,
        134,
        135,
        136,
        137,
        138,
        139,
        140,
        141,
        142,
        143,
        144,
        145,
        146,
        147,
        148,
        149,
        150,
        151,
        152,
        153,
        154,
        155,
        156,
        157,
        158,
        159,
        160,
        161,
        162,
        163,
        164,
        165,
        166,
        167,
        168,
        169,
        170,
        171,
        172,
        173,
        174,
        175,
        176,
        177,
        178,
        179,
        180,
        181,
        182,
        183,
        184,
        185,
        186,
        187,
        188,
        189,
        190,
        191,
        192,
        193,
        194,
        195,
        196,
        197,
        198,
        199,
        200,
        201,
        202,
        203,
        204,
        205,
        206,
        207,
        208,
        209,
        210,
        211,
        212,
        213,
        214,
        216,
        217,
        218,
        219,
        220,
        221,
        222,
        223,
        224,
        225,
        226,
        227,
        228,
        229,
        230,
        231,
        232,
        233,
        235,
        236,
        237,
        238,
        239,
        240,
        241,
        242,
        243,
        244,
        245,
        246,
        247,
        248,
        249,
        250,
        251,
        252,
        253,
        254,
        255,
        256,
        257,
        258,
        259,
        260,
        261,
        262,
        263,
        264,
        265,
        266,
        267,
        268,
        269,
        270,
        271,
        272,
        273,
        274,
        275,
        276,
        277,
        278,
        279,
        280,
        281,
        282,
        283,
        284,
        285,
        286,
        287,
        288,
        289,
        290,
        291,
        292,
        293,
        294,
        295,
        296,
        297,
        298,
        299,
        300,
        301,
        302,
        303,
        304,
        305,
        306,
        307,
        308,
        309,
        310,
        311,
        312,
        313,
        314,
        315,
        316,
        317,
        318,
        319,
        320,
        321,
        322,
        323,
        324,
        325,
        326,
        327,
        328,
        329,
        330,
        331,
        332,
        333,
        334,
        335,
        336,
        337,
        338,
        339,
        340,
        341,
        342,
        343,
        344,
        345,
        346,
        347,
        348,
        349,
        350,
        351,
        352,
        353,
        354,
        355,
        356,
        357,
        358,
        359,
        360,
        361,
        362,
        363,
        364,
        365,
        366,
        367,
        368,
        371,
        372,
        373,
        374,
        375,
        376,
        377,
        378
      ],
      fileOneLines: [
        "public class fOr54jzw {",
        "private XhX o(phy Li2, RUzR EGE1, HtNtb bxHZ3s8, RFWodpN0O F9H, p cznoGBrW) {",
        "if (CEhFo + g * dOYzBzX) {",
        "if (HgYNkFm < al5HPnc > T8Qb35) {",
        "gGV = B9omveUTf(jzz, LG7I6pHs, seactT58) + o < oKRiTOGYX;",
        "oJd_30yhs = cY;",
        "Q4O3uZ = FJ5ci_fF * _ * Zf_KF(gT4_gCfzB);",
        "jei5b = h * aqbl7gcaq + yikUA * NgUEYWG;}",
        "if (bAuW > oYXt(U, Bg)) {",
        "KWD = tUpY2VJ(hIpu < J, JLNcLxR0);",
        "Sb8FDgDT = GOh < ou65L7z + DS;",
        "mH djSjX4l = RD();}",
        "else {",
        "z = rvnCL + Rz03A;",
        "wRULGaD7N pfHRfQ7ak = T3cxhTqM(S_u4OXu6s, WFdHh6GDC) * pIMmDDx(XWATW, uQZnkL, q73Kq2roR);",
        "r6jP2 W7ihd1Q = fFCmZib7x + Vdfd < oB + CItMR;",
        "S gyijSwfh = DhNH + S * tTz2VSfm;",
        "D7yZPBMZ Ojo = PrnV;}",
        "iwaI9afuZ = kTnkLQajL(JDVxoQ) + tAMNYS(oPDFLpi, JhJng2K, nX_O8);}",
        "else {",
        "BzeJ3CA6m Awtd = Et;",
        "while (E6tm7gM8 * g0iHfmY > tDm(U)) {",
        "MI = PS * q + c(tf3DCb, vpMapvmcN);",
        "ugye_cm = jWvXErd5s + kdFrZ * JKBkvM(k7, P741B1S);VV81Z0YaJ = d > HRbcD0 * A;",
        "}",
        "if (bxbfvtpAT * EI365RYQ * EwP) {",
        "oXPaHR = PJ(N, SUm, SFrrk7V) > nP * cdz;}",
        "for (RTw0sDb2 = vnF; CPm9Akr > FTrtNA5 < hnx; v9gVbEtk = m3TdCn7O) {",
        "cUxx = PAvsvn(OpK(), PV < N, Q4C(grwlEWF));",
        "sZBIo8bn = Z < bMU4X;",
        "H7NuCgkf tsLhRz5A = ijN4uzxs * GU5 < A + NXVyHk1;}}",
        "n0 RzB = WH;",
        "Q W = iNofadFFZ < lbA6eC < xsRHKN1B;",
        "while (k64H * XHzqrMA2 + WTx + Pe) {",
        "if (_gfXR8a36 * sfZ < Krr + OTzL5) {",
        "f2ck = XrOjygc + P * uY > VW2c6;",
        "U = VjcsCkMo0 + LJLTwOsk < s5nH1 < kkJmKO;}",
        "else {",
        "YLKyK0nn sRX_v = lqZ72v + yD1jsLyP < MIh_;",
        "v7sn3k8 = IZ0jU < Nsr + Yz_Bnwte;",
        "NbvROpp XmFDyb5C4 = wNuCgd + v8z4F5MYL > lkRu6dQFg + XY;",
        "Wpyn = CyZ9V;",
        "FEbV Xfs46F1o = TQp_ > lD6vwv > brLc7h;",
        "T8S gqQ = G1dW * hGX9Rw6T + Xh1xAOJxh * tXTTW5vT;}",
        "ra_R YZf8Z = vRMD + wJrYQLq1 < BusXKa * Y;",
        "for (ueKj0 = uDg5x3M < edo > xGeQsaJ; p(Dxjsd + TmDJ, M7tNwdbU * lLD6n); OI9Y4sb = jlKCZ < J5_rrMR + kR4Ej9x) {",
        "fd_BrVN = QoWXC2;",
        "uYEYVd = W9JBG;",
        "PiBGK = k048DO * vRRh0Q + u;",
        "tpSfc1xK geJJd = tLVCVu6Zu;}",
        "RR32m JuTFi7_BA = INuXEOKKH < zdbQ * Dw;",
        "for (I8i7u objfF = V(gddnfzS(), BDfT + pH7y3XhU, gVMKkf); ypJD > ICoKh * Bjfuql + kR8g; BF = KLIfLbf > NL92y + t > A4Y5Av_1) {",
        "Z_TAkLAy DqmA = FzCa;",
        "nr = kZ8JLN() * m * HfySS;",
        "xkpb = Zjh1 > SAb * SyRm7KXFZ;",
        "sN adLqS = InxG9d > P > Vy1rD7S < W1ORjKiSG;",
        "R1sFn5Ri YDTuzW = MBGYMENu * oRnoppqU > x_DNVCc9 > UzyVfrQ4;}oVPg2UJ = qutYWj9Q;",
        "}",
        "RO = E4jE > jZXNMga * dtSh1B * lGTpkf;",
        "while (j9 < W0J < y()) {",
        "O6DlCXd = Q;",
        "while (jvKxyn) {",
        "YB kl = fUbG(zUse, fLrmsPi < y);eVHa7Hf = o > y_ > QXzep2cL * L;",
        "}",
        "if (_Clb4m0 * r7xIzLXeN * cGADKK()) {",
        "m bdq = kG6AfOZ;",
        "pW = Tyq < wf + _G < A;",
        "IKIzcBJ = wEmLdBn(sh) * DzFndPF < KyBu;",
        "GhOjY4 = v * szwu + UfKvMtDSx;",
        "mvBjfx uUY = M12eK(F1eflUI, JyYsWf) + vW > nfTV;}kH = G();",
        "}",
        "nWG = p5 > UNWNVf7S < g3KXmqPv < up5lT;",
        "while (I(YBwFbTKL * aK, EX98 + LRDLX)) {",
        "KJ = kGCPg * MEPhx2GE + WXi0N;",
        "while (pMDpvYL < lMaqG1W + wJxl(xy52ugZZr, HNr6fm5, YhjpW)) {",
        "nj egFjZJG1W = xLcPW > Ka7Lh9j < p1o1 < UN;",
        "U7q y95T7l = INUjgI;t = z * oS2SZazy + yEpKiJ8 > c;",
        "}",
        "for (U = hlz9F(Jbt + JzzHupV, qF9oWv + ay5Jnk2, sJ * a); OufT8; b3 = p0WJeS > BUjWGCY5 + oZu) {",
        "G1R4 = ioiHPFp5s() > QrjxtW < qFwpE;",
        "JFz HwH8bG6XK = iJcAS073 + cx4qpL > lpZ54 + R;}IBsMgRQF = BxJ > _cu6 + G853Zi_(Wur0);",
        "}",
        "X3gzlf_ = ZNKwc3I;",
        "while (zC) {",
        "for (H = JeSn(x7 > V); FveIb(aU < Igl7, IU9); G57z = zCvF > sqgG + O + aboEEYcXW) {",
        "LDN = mX * Q < OeM2L * zx;",
        "_ = CAEdl9IFy + cpXd + t + IG;",
        "r = pZ * TL > nux;}",
        "if (sZf7()) {",
        "J2 BPWpRZ = ZIZy6Op3(gFXq6Jg(Z), YWXbmdj + tKBYE);",
        "Kg = nuo + lJHAYYI + xvrUyTU * JCkWB;",
        "O = K__3z * H0U3LBx < _uv();}",
        "else {",
        "OtwkdYPH = pI5uW_Fco;",
        "NlkKdV = v * M8xONnGW > SUR2ob(mtdxvaih, FnNDNWM, RJ);}",
        "jZRhhZdc = MdRbbo9D < B9;B = Yv * jWyzDxtVX + fohk73Wp > HW9;",
        "}",
        "Y tI = gtbLJ(N6My, _bXtq91) > Q4m + Q7ZFSZMJ;",
        "if (XGSc5WYjF * _2nPws6q_ > yfQVYmy + FCUqwp) {",
        "for (BJ5g2fpx = WKDavyUTd; N < HqBWChD; xAAgFUR3 = H + K9BflLMB + RzVNzj59) {",
        "yrd mYH7 = oq8t40Hn1();",
        "U651CHGWl = DMVI * TbjfbxU < vfPKphw_ * IIraADb;",
        "tRsh x40fbzTF = eziN > mHDF + ID6RzIE + pnt;",
        "D3 = XhF(BCQ2, MVMJSKL) * Ix1v > aGp3aYy;}",
        "for (Lg2P6i dlaOC0CB = InFvS + OGQE + g * Q; i + n14VfM + NZtlIwN + t8qe; r = zS(LQ7ak, zpZWZpC, ZBxj) < q + _) {",
        "m m = qtjgA4kN * SLOXNXhX * rvfvm > GJMMxT8;",
        "c0 EyI2O513 = ZE;",
        "MXmYY = J3 * ePZ + _0U_ > LTOEslr;",
        "VwstT = MUS1GBA42 > MbA0 + VBbcH;",
        "wn_uHsXW zMv = ftI1 + q06gW3 < ScAJ < NZ9m74;}",
        "for (T2jLtmxGq txirYZZx = VNp * H31am4iFF > uy; t + YwRfQ + SNB_BdCTC; mUPzJahN = gGkwv2B) {",
        "D = Yc;}}",
        "else {",
        "wIFNSu = Siie4xPO > PqVdTeT < _v;",
        "while (XWjq < Yvm75BpXy * Q4O8D(L1ng166j)) {",
        "uf W5NaxZH = ckYENWhO + r9ZM7 * S3Ssa(FkCl5YV, L, Xm);",
        "r06YW2uv wEX2MdOI = H > llbeHrdzC < LkuZnM8 > j;Z_k1V = X + RXS < aN > LeLNuSoaa;",
        "}",
        "if (OwoM5u(hnVJ_cM > FILimvCY, Qz > ae9H0hL, kGDDM + oDU)) {",
        "jntXO DJQjrCd = ScwkDGnaM < fBMWu + Km;",
        "r0s0F9GfM = xR;",
        "EkRWr = cxi1;",
        "PetqL OozT6n = B;",
        "pRw iq = aTyS4zO2f(rPPQZ4iK, CDUhE, JoAPVSz) + a4K4 > qb;}}",
        "for (ganDjwqVH = xz8(L_1, ZrNmt55 > e4Se, F > atySuS4L); mgY(zT > pV_sv); ekJMt = VvOxT2vv < oI3Udq > L) {",
        "Erwp44U vBzE8grs = noV5cHexy < UvS4b > q(NrLkSBj, L, wDed);}",
        "for (kB FPdnDW1 = wjH4() * F4eCE > Xq_SdNZ; mbL; R2 = zfAoBE > Ut67VSLVa > Vgjlr * p) {",
        "T = JSxt4Qsm3 < FMwcj + anravN + LjIqKil;}}}"
      ],
      fileTwoLines: [
        "public ",
        "",
        "	",
        "	class",
        "   ",
        " BM",
        "",
        "	 	{ 	 	private		   kJEI9u0p",
        "	  ",
        "	dO(cYtg    ",
        " Z6,",
        "  	",
        "	  LI6fpEY ",
        "    nAKceNmGa,	",
        "     _jFc9Y5i  ",
        "   Qhs4xU,",
        "	",
        "  M 	 	  ",
        "zSY7ncYW_,   	 e2  ",
        "  	 FBKa)	  ",
        "{ 	  	 gigOWD8  Ur",
        "	",
        "	   	",
        "=    ZS6ZL; 	",
        " ",
        "	 if	",
        "   (Pe2",
        "",
        "",
        "  *",
        "",
        "    n  			+  ",
        "Iyz)  { 	 	",
        "",
        "",
        "if	  	 	(J(n, ",
        " cy_Q2x)",
        "  	<",
        "     ",
        "Qd)",
        "",
        "   { eSjOde",
        "	 ",
        "=	 ",
        "	 Kwk3RZJqV",
        "   ",
        " +	 	",
        "   ",
        "	 mM ",
        "",
        "  >",
        "		",
        " 	z3fY2ej4;		",
        "",
        " 	VhSev",
        "   =	 ",
        "",
        "	lBg(cVqNKeT  	 >	  ",
        "	  ",
        "HU, ",
        "",
        " 	",
        " 	 	 a); ",
        "			HjRm",
        "   KqNOVCTf",
        "	 ",
        "",
        "=	  		 JRW3JPwHo();}",
        "",
        "	 ",
        "	else ",
        "{   	ZvAz ",
        "",
        "	 fYpyDttD3 	",
        "",
        "	 ",
        " =    E(HOV,",
        " ",
        " 	 	hUUj5BfK, ",
        "",
        "	",
        "i9MuHMMOf)",
        "  *  	 ",
        "qkwrOHLWx(BUwWsZ,  ",
        "   	e); 	 ",
        "	cQSLo 	 		=	",
        "  	 	",
        " PD  ",
        "	 ",
        " + 		  	e56;  	 	 ",
        " 	hb8MA",
        "  	  XHcDz	  ",
        "= 	",
        " ",
        " 		",
        " Z9	   	 +",
        "    ",
        "IdO3h29c   	 	 >		  ",
        "",
        "  gKajrK",
        "  ",
        "   +		  ",
        "",
        "  ",
        "	yL_e6o1A;",
        " 		Nh    j  ",
        "		",
        "",
        "  =",
        "",
        "",
        "   	  IVBni7j",
        "",
        "",
        " * ",
        "",
        "	   HWe7	",
        "",
        " +   	 w3Idk046; 	",
        " ",
        "",
        "	 JQvS1lev",
        "	 		 ",
        "  WTk	",
        "  ",
        "",
        "  =",
        "  ",
        " S4JzpC;}",
        "	     if",
        " 	 ",
        "  		 (gQc",
        "",
        "	 <		 ",
        "wr_O	 	 ",
        " ",
        "	>	 ",
        "  ",
        "",
        "  IivRhR4Q)  ",
        "",
        " 	  {",
        "",
        " kLST  	 = ",
        " 		 ",
        "EoT; ",
        "  	xYtBN ",
        "	   	=	    ",
        "",
        "		BEzmfie4 ",
        "",
        "		",
        ">",
        "",
        "",
        "    YzQ  ",
        "",
        "	",
        "	+ 	 ",
        "   	",
        "",
        "	Gc(NNo,	 	 	",
        "rWBCEhzZ, 		  ",
        " tDDWiJPR); 	   ",
        " atp",
        "    =		",
        " ",
        "xTmxG3EfR(CRSSC6z) * ",
        "",
        "",
        " h ",
        "	   	",
        "*",
        "",
        "",
        "  		  	NcWo6;",
        "",
        " SJoitPKwW		 	 =	",
        "     ShvJQHLSN	 ",
        "   	*  	  	o		 + ",
        "",
        "   	 Lm0H +",
        "	",
        "",
        "	 r; 	",
        " ",
        "   xq  	",
        "",
        "",
        "   	=	 	  O2Uhvuf 		",
        " 	 ",
        "*   		",
        "",
        "	bBsiIgiS",
        "",
        " 	+  ",
        "		   ",
        "	",
        "eWF	 ",
        "    * 		 vv1yk;}  	  IM",
        "    =",
        "  	FtO(f, 	",
        " ",
        "",
        "	aiNnCl, ",
        " 		  ",
        "",
        "X0l)	 	 +    jfBw1UciQ(W);   	 	 P",
        "		 	=	",
        "	   	gTR4uM(f,		 YL3zJb	 		<	 	mMJ);}	 ",
        "  ",
        "",
        " 	 	else",
        " { ",
        "",
        "			if ",
        " ",
        "	 		 (a 	 * Dk5avqID ",
        "",
        "   	 *     mcD90P)    	{",
        "	",
        " cS4wcj",
        " 	 	 =   		",
        " 	oiQOas	",
        "",
        "	  	  *",
        "",
        " ",
        " 	YDleL ",
        "   ",
        " <		 	    SoOoL(_x_bOKEa,		    YenxCE1v,  ",
        " 	 		",
        "znZ2mwXc);}",
        "  ",
        " RJ0x5x ",
        "   	",
        " ",
        "	=",
        "	 ",
        "	Z1Z8 	 	 	>	",
        "  	",
        "  L5OEt 	 ",
        "",
        "	 +  ",
        "		",
        "  OD7 	",
        "	   ",
        " <",
        "	   ",
        "",
        " qKhf5k4gc; 	kSP    	",
        "	 lHDIxn   =",
        "  YcwkKwb5 	 ",
        "	",
        "   ",
        "+  		 	",
        " ",
        " ",
        "_E5		 	    + ",
        "",
        " ml0",
        "",
        "   	 >	  ",
        "	p; ",
        "  ",
        "  for	 ",
        " ",
        " 	 	",
        " (e5mV6		  	  ",
        "",
        "",
        "NPP1_x72    = ",
        "    ",
        "",
        "	ZT;	",
        " ",
        "	",
        " 	LY3jkD(G1wPB) 	 		   < 		  	 Mgm6M ",
        "	 ",
        " 	 * ",
        "  	",
        "",
        " zUBk2rOdS; ",
        "  		",
        "",
        "gkymQ     =  ",
        "",
        " Lh ",
        "	   ",
        "*",
        "",
        "  ",
        "lJO   	 <",
        "	 	 PjjEO) ",
        "",
        "{",
        " 	",
        "UUK",
        "   	",
        "",
        " E",
        " ",
        "    =	 	 KPgbkh81",
        " 	  	 	 >",
        "   ",
        "	 tE ",
        "+",
        "",
        " ",
        "SyX ",
        "	 ",
        ">	 	",
        "",
        "   ",
        "iSrlQj;  ",
        " lP_E",
        " ",
        " =	",
        " ",
        " ",
        "fC(gy6ZX,	 ",
        "",
        "",
        "		TxzxeP) 	 ",
        "",
        " 	 ",
        "*",
        "	 		SLN9TPjs6",
        "",
        " 	  ",
        "	  +",
        "",
        "	    ",
        "oN3;  ",
        "",
        "",
        " tIKbO	 ",
        "    ",
        "",
        "=			 ",
        "",
        " ",
        "ZIIxiw(e0_zU,	   	  	kA)",
        "		 	  +		 	Yq   ",
        "",
        " * ",
        "	",
        " ",
        " Tmn;} ",
        "yK	  		",
        " ",
        "= ",
        " 	",
        "	",
        "hY;",
        "",
        "   			while",
        "",
        "		   (TGJtt ",
        " 	",
        "",
        " > 		 ",
        "",
        "	",
        "  y8u ",
        "	<",
        "  ",
        "	   gacHZqI) 		 ",
        "",
        "",
        "	{ 	 ",
        "",
        " Pp8Wrigj2	",
        " ",
        "",
        "	   =     NR(lo(),   			 ",
        "tQjbcI 	   ",
        "		>	    		 Ml,	",
        "	",
        "	 HzCDQcX8A(eC));",
        "",
        "   ZFUMfDcRD",
        " 	",
        "	aQ3Zxw5 ",
        " 	 ",
        "  = 		",
        "  	 uLaWG71 	 		 +		 ",
        "",
        "",
        "St",
        " ",
        ">	",
        "	  	hqAn	 	*   	",
        "		  iHmMmA;	   Kn1",
        "",
        "",
        " =",
        " ",
        "  	TgrtW1Dj(Ih_fC, 			  s2dPhmHQ) 	",
        "",
        " ",
        "  * 	",
        "",
        "M",
        " ",
        "  ",
        ">	  ",
        "   		B; 	",
        "",
        "	 ZTuG",
        "		 	= 	",
        "		u",
        "",
        " >			    AOE2akRW   *",
        "  ",
        " ",
        "tC();  ",
        "",
        "",
        "		 	 KX 		 ",
        "  	",
        "=	 ",
        "    q7hxC    			>	  	 ",
        " Bu_wd28;ApQ   = 	",
        "	",
        "	",
        "XA8TnrX;	   		}}	 	 for    (fKGHkE ",
        " 	  	",
        "",
        "	v8     ",
        "=  TbNKoj9tI    	 >			   YjUSH6 ",
        " 			>	   ",
        "",
        " wUD;     jBf8B	 	",
        "  	 + ",
        " 	 	 ",
        " Fc5V",
        " 	+",
        "		",
        " 	    ",
        "cW 	",
        "",
        "	 	*    ",
        "xa0RPRx7;",
        "		 ",
        "	JkSWX7	  =  		etA)		",
        "	   ",
        "{",
        "  		TgL68Sm9d    	fiE7o",
        " 	  = ",
        "j4vNAKrY 	  	*",
        " X4lguV    		>  	",
        "	",
        "	w4  ",
        " ",
        "+  		   	rPXH0;",
        "",
        " 	 if 		",
        " ",
        "	(p   ",
        "	 ",
        " ",
        "+",
        " ",
        "   	lSC	  ",
        " ",
        "	",
        "	> rND2sk 	 ",
        "",
        "	*	  ",
        "",
        "  ",
        " ZRG)",
        " 	 ",
        "   {  ",
        "  	DeFmST 	  ",
        "	",
        "	= ",
        "",
        "		 ",
        "	_qVGuES4C    >",
        "",
        "  xb8JHmgMD 		>     JArepy 	",
        "",
        "	   +	",
        "  _FUV5_DvF;",
        "	",
        " ",
        "   vx2_U7GGl 	  	 	 =",
        "",
        " ",
        " b",
        " 		  ",
        "  <",
        "",
        "",
        " KhiZwL2 ",
        "  ",
        "  *	",
        "",
        " 	 ",
        " eAivB",
        " ",
        "	",
        "+",
        " 	 ",
        "",
        "m12aWL;  	  	q	",
        " 	",
        "=	",
        "",
        " 		QUhlQ1Y",
        "     	>     ",
        "zpSCXS",
        "    < 	  	",
        "",
        " kumtEFEig	    ",
        "	",
        "+ 	  ",
        "	 	 Hf9SK2HY;		  HH2j	   h0n5R  			= 	 ",
        "",
        "	 l9oxV  	 		> 	 	 	 uFwafz     ",
        "+",
        "",
        "	   	 WVFh8",
        "	",
        " ",
        "	<   ",
        "  ",
        "_jxuDk2Y;} ",
        " 		",
        "",
        "else",
        " 	  ",
        "",
        "{	   	  YHxwY6cG9  	  	x9oBW9aj",
        " ",
        "",
        " 	=		",
        "  ",
        "  ",
        "	ivwu ",
        " 	>   ",
        "	YT4cN70rk  		 +",
        "",
        "     ",
        "BaI0yUs;	 ",
        "	G4D",
        "  ",
        "",
        " 	 =     zrL6		 	",
        "",
        "+	  	 ",
        "  bjzrar_c5	 	",
        "	",
        ">",
        " 		 	   Lwwk; ",
        " 	 TFp18y3  wP ",
        "  = 		   	DN	    + 	  	",
        "",
        "	",
        "bq ",
        "",
        "  ",
        "<    xYw3Ah9e",
        "  + ",
        "",
        "			 ",
        "  P; 	",
        "   ",
        " 	C7cLt  	",
        " 	 	px4g",
        " 	= 	 ",
        " ",
        "",
        "  GUQhy  	 	",
        " 	<",
        "	",
        " VI  ",
        "",
        "	 ",
        "	<    zZ9g3g;",
        "	 	 ",
        "	mZRxFV     ",
        "",
        "= 		",
        "	 ",
        "KH57o;",
        " 		",
        "zsdno",
        " ",
        "",
        " lPZCQhsu2  ",
        "",
        "= 	",
        " mB; ",
        "	",
        "  ",
        " 		 FwZ7m  	TDVz5o",
        "	    =  		  l9wScyJV 		 	*",
        "	 	 b  ",
        "",
        "		",
        "+ 	 	 	  Z9Va	",
        " 	   *     Vy64MNgzU;} ",
        "			D4vG 	 =",
        "	",
        " nIzTQAex  		  < ",
        " 	Tjq5jo  > 	 	 oeeLJ2aD; 		 ",
        "  ",
        "",
        " 	while ",
        "  ",
        " (Ly(qc",
        "   	+	 ",
        "j6I8h3y,			  xKUDya_   	 	 *	  	  zEPPb))",
        "",
        " ",
        "{ ",
        "ByHZNjNa",
        "	  	",
        "",
        "=   ",
        "		 ",
        "ZSHy; ",
        "   CbU1VoM	 ",
        "    	= ",
        "",
        "",
        "  SV",
        "  ",
        "   +  	X5xYg	 	* 		 	   UBc97hADf; ",
        "	  	 	t3h	  ",
        "  ",
        "=		  	rzpB2d;	 ",
        "	   b   	",
        "",
        "rTt5GAL ",
        "  	  		= 	  ",
        "	K;tTm	 ",
        "",
        "   =  ",
        "			h4B_N3",
        "",
        "    +	  	  GEyvG	 	  	  >	   ",
        "  		",
        "i; ",
        " 		 }	",
        " 	 	 ",
        " VCR",
        "	 	 =",
        "  ",
        " ",
        "  C();",
        " 	 		UQkeIcmFh	 ",
        "		dQIc_Z	 	",
        "	   = ",
        " 	",
        "	",
        "fCK	  ",
        "	",
        "",
        " 	  *",
        "",
        " NNI_sswV	  	 >	 	    ",
        "	WVgwgBqbO;",
        " 	   ",
        "	XcDR",
        "",
        "  J8_cUnkfW    = ",
        "    	",
        "nMaof(Cnn(),  ",
        "  ",
        "",
        " s   		+",
        "	 ",
        "	 ",
        " d,",
        "	 U5pTN2YS); 	",
        "  while     (SxHNhBI   		",
        "",
        "",
        "+	 	Fxv9l0YHd	  *   ",
        "  ",
        "R8x_6998p",
        "   	  <		 ",
        "	  ",
        "p)   ",
        "  {  	 		 xvh",
        " 	 DUJpz	  ",
        "= 	",
        "",
        "",
        " kO; 		",
        "	 ",
        "  ",
        " uBQyuT9N",
        "",
        "	 	",
        "	  =	",
        " 		 m7fDVP 	 *	 	",
        "",
        "lDl_FMmjJ ",
        " 		*    W9();	 		 ctkDz7I 	",
        "  ",
        "	 hd1rgr 		 	 ",
        " = ",
        "",
        "	",
        " 		eSCGD		 ",
        " ",
        "> 	",
        "  ",
        "		  ",
        "Lx_uYnU     ",
        "<  ",
        "",
        "  ",
        " tRO3T  		 <",
        "   	",
        " 	T;",
        "  ",
        "   dbuCEkitm",
        "",
        "   =	",
        " ",
        "	 	SSKH	 ",
        "		*",
        "	 ",
        "",
        " YRUMi7V	 		<	 		 ",
        "  ",
        " MJu;",
        " ",
        "",
        " CRzbZbb		   M_alGwS 	 =     Xh3VkKeWT ",
        " 		",
        " 	",
        "<",
        "",
        "	 ",
        "	   TM",
        " 	",
        "<",
        "    ",
        "Yr *   		  	S;iTjqc  	 	= 		",
        "baJWHFr  ",
        " 	 <",
        "",
        "	 	wMepVE3g  	   + 	 mknfhGd	",
        "	  	 ",
        "  <",
        "   	  ",
        "	",
        "JRVysX3z;		   }} 	for 	",
        "",
        " ",
        "   (oSq9Rsv7	  = ",
        " ",
        "",
        "  dcn_8OhKY  ",
        "",
        " * ",
        "	  		  IXY",
        " ",
        "   * 		 	",
        "",
        "GWT6hXZN",
        " 	",
        "",
        " < 	",
        "",
        " 	 sxfZsA;",
        "",
        "  			Jm6Gx()  >	     		",
        "c4QEPyqb		 >",
        "",
        " ",
        "	PdAHaI;		 ",
        " ",
        "lDmZTt",
        "  = ",
        "	",
        " ",
        "	TDIvV7())  	",
        "{     c5L1e",
        "		 	= 	 	",
        "",
        "   	",
        "Hm9AFMo(F2KoE0W(ruT81ijh),   ",
        "  Cf 	  ",
        "",
        "",
        "*	 	",
        " 	ro);	    	if  ",
        "",
        "(Oy() ",
        "	   	",
        " ",
        "	* c4a",
        " 	",
        "    * 		 	  vPM) ",
        "",
        "	",
        "		{ 			",
        "   K9i9R	 gMFgc ",
        "",
        "	=",
        "	 ",
        "_  ",
        "",
        " ",
        "	 	*     fvTHNh	 	 	",
        "+		   CxB",
        "",
        "",
        "  	 > 	   yCaF;",
        "  ",
        "",
        "	 xKNka			",
        "     n4ZN",
        "   =",
        "",
        "",
        " pktpXq;	 	 pQ9HfB",
        "  	 ",
        "",
        "  =  ",
        " 		",
        "	 ",
        "cFE9a1G >  ",
        "  ",
        " ",
        "	H1njfqGoc	",
        "",
        "",
        " *",
        "",
        " JyB8(o2JNarRwO);	  ",
        "",
        "LD_Kaap	 =",
        "  ",
        " ",
        "YEX  ",
        "",
        "	 	  >",
        "	 	  ",
        "  rqk	   	  + 	lw >    ",
        "bt;   ",
        "x5vSpB  ",
        "	",
        "=     sNQe9G  ",
        "  ",
        " 	+			  _p	   ",
        "",
        "		 *	",
        " ",
        "",
        "   JUCTZ;    	 Mj8 	",
        "",
        "",
        "=  	",
        "vmKusr(np_0, ",
        " VJ7rMK93N	",
        "",
        " 	+	",
        "",
        " ",
        "  wa4Y1);",
        "",
        "   ",
        "	 FP2Zn5wg  	",
        "",
        "	   	_H6DPs75  = ",
        " ",
        "",
        " p9F1 ",
        "	",
        " ",
        " 		< 	  ",
        " 	 ibDwuPmN",
        "",
        "	 ",
        " 	 +	 ",
        "",
        "	JFn(C,",
        "  	  	 kUSm_0Gg);}",
        "",
        "",
        "  for		  ",
        " 	 (Txc 		 ",
        "	 =	",
        "	 	nCR0iQvJ; 	",
        "  Htg7;		 	 bMwF 	    		= ",
        "",
        "Tt4Fq0NUZ 	 *",
        "  			g9cpf	  ",
        " 	",
        "<",
        " 	",
        " ",
        "p6  ",
        "  ",
        "	 	< ",
        "	",
        "XX) ",
        "  		",
        "",
        "  	{",
        "		  l   		 	 ",
        "k  	 		 = ",
        "",
        "	   	",
        "wHsVVW8GD(h_,  ",
        " ",
        "",
        " w8ahUGQ ",
        "",
        ">	  ",
        "",
        "  r2Tj);		  	 ",
        "",
        "GC	 		ALt6G99h  ",
        "= 	",
        "",
        " T5Xlk2    	",
        "	",
        " < ",
        "",
        " d   	 ",
        "",
        "",
        " + 	   pa  <",
        "",
        "   R605;  JXjnbkN ",
        "	  ",
        "	",
        "  	=",
        "	",
        " 		XWgr_(N4JzXnF)	 	 	",
        " ",
        ">	",
        "",
        "    	",
        "Oi8YAsz",
        "",
        " ",
        "<",
        "",
        " Er1B0Lq;}} 	 	for  	  (QdTCJAckq 	",
        "",
        " ",
        "  	 = 	   	q7sH  ",
        "	",
        " ",
        "> ",
        "  	 ",
        " aLsnd  	   > 	",
        "",
        "  ",
        "JAl",
        "	   	  <",
        "	",
        "	",
        "	 A;  FlKor_(LxX",
        " 	    *   ",
        " ",
        " edBav,		  ",
        " v7Jr5r ",
        "   	 	",
        "+ 			 B5IX);  ",
        "",
        " 		  	",
        "NhX9Ffbp 	",
        "	   = ",
        " ",
        "  qZbvJ5j(aNerjvN)",
        "   ",
        " +	 ",
        "",
        "",
        "	SC  ",
        " ",
        "	",
        "<  ",
        "",
        " 	",
        "  uIKzeqiT)",
        " ",
        "	{ ",
        "D7bktHP",
        "  	",
        "=   	",
        " 	",
        "	",
        "V(GNvoYDiyZ			 +	   	  	unWygIUG,",
        "    ",
        "",
        " nM9zm8u  		",
        " ",
        "+ 	X2oAk,     g6	 	",
        "",
        "*",
        " 	 mAX);	",
        "",
        " ",
        "		while	  		 (PWSxf) 		",
        "",
        "	{  	",
        "	",
        "AR7bjTTt1     m8Y ",
        "",
        "  =		 	   v1pU",
        " ",
        "  ",
        "  +",
        " ",
        " 	 	Iu 	 <",
        " 	 		",
        "k4c_K2Mp	 	 	+",
        "",
        "",
        "    KUxIHSa;",
        " 	 ",
        "	GVtxbXDBz		",
        "",
        "",
        "  =",
        "	   ",
        "uAvdj53  ",
        "",
        "",
        "  	>   ",
        " 	 qQYkKl	   ",
        "  <",
        " ",
        " ",
        "   Kj();jnDkffb9w ",
        "	",
        "	",
        "=",
        "   ",
        "",
        "h    ",
        "",
        "+ ",
        "	  ",
        "  ",
        "ut_0",
        " ",
        "< ",
        " 	  bFtxeMHt;  ",
        "",
        " }    ",
        " ",
        "",
        "for	 	",
        "",
        " ",
        " (MLLSMH    =",
        "   LqO    	 +     hzgW 		  ",
        "  ",
        "* 	  VFkl8dEp5;  	  dC45wYwA(gfMpQU,	  	 Y,",
        "",
        " 	q4jAaVX) 	  	 +	   ",
        "",
        "  aJD1p",
        " 	  ",
        " 	 ",
        ">",
        "		 ",
        "	q;   ",
        "",
        " ",
        " mHC2PbLUX  	 	 	=	   	 wk7nPGxEe ",
        "  <			  Zm",
        " ",
        "",
        " 	+",
        "    	",
        "",
        " UBmP",
        "   ",
        "*  	",
        "	yx)  	  	 {  o6	 	  uBwmfMr    	 =	   ",
        "	 krEc9; ",
        "	 	BSd80pY	 	",
        "=",
        "",
        "	   ",
        "uKhb6_DsP  ",
        "",
        " 	 > 	 	  	QQDn	",
        "   ",
        " 	> 	   ",
        "i2JVKg;",
        "",
        "",
        "  mJdO_TeP0  	  =",
        "",
        "    iqfGq6  ",
        "	",
        "",
        "*		  ",
        "",
        " ",
        "  Z5a7 		",
        "",
        "",
        " >    	 ",
        "",
        "	y59D7F6;  		kHnW",
        "	",
        "",
        "  		RL ",
        "",
        "	 	",
        "=	  ",
        "",
        "",
        " Y50WSr8f 	 >",
        "  nKLH6z_  	  	>	",
        "",
        "	  	g ",
        " 	",
        "	 ",
        "	 <",
        "  ",
        "",
        "Svp9YI;}",
        "",
        "",
        "	 yTZNobr",
        " ",
        "    s  ",
        " ",
        "	=	  		 OalD(); 	",
        "		",
        "",
        " S2eiel		",
        "",
        " ",
        "	lZAMB	",
        "",
        "  =	  	 zPxADnY(nlvRkF7y",
        "",
        "   ",
        "+ ",
        "  		  ",
        "yB2I7o,",
        "  ",
        "",
        " f4 ",
        "  ",
        "",
        "<  QMW,  		",
        "   	wfxAZv  ",
        "   ",
        "+",
        "  ",
        "g);}   	tSx5   ",
        " 	PHTON  ",
        "",
        "=",
        " 	r_2G9hV0	",
        "   		",
        "+",
        "",
        " ",
        "  Yd 	   <",
        " ",
        "CbGzRx(g7hMZJ,",
        "",
        "    ",
        "cPzrOB);		   	 for	   	",
        "",
        "(c	 ",
        "  ",
        "	= 	QxY;		  fy;	",
        "	 	",
        "uMqxa	  	  = 		 	 VhO7     ",
        "",
        "<		 	rW0Q + 	",
        "",
        "  	 	T71y",
        "  	*	",
        "  y)	 ",
        "	",
        "",
        "{	   	  if",
        "  	 		(aIK9FP())  ",
        "   ",
        "{	 		 ",
        " ",
        "oEwFTJb	  ",
        "",
        "",
        "=",
        "  ",
        "   DrQ8nWND ",
        "  ",
        "",
        "*	  	",
        "	",
        "X3cj",
        "",
        "",
        "	  +	  		HcSw8WR6 		 +",
        "   	",
        "",
        "	isI; ",
        " 	   LefEFXT  ",
        " 	 ",
        "d  ",
        "",
        "	 ",
        "	=",
        " 	  ",
        "  gJ9BhF(WDyTZH1(x1UQvH),	 ",
        "	ip	    	",
        " ",
        "	+",
        " ",
        "	 fg);	",
        "		",
        " HWu7rrL",
        "  	",
        "   ",
        "	=   	 DDl4()",
        "		  	",
        "",
        " > 	",
        "	 ",
        "",
        "l01MFCyWH    *    ",
        " ",
        "",
        "bT;	 	 cFuZWpt  ",
        "	 ",
        "	grP9tLve	 ",
        "",
        "",
        "= 	   ",
        " E6Q5B",
        "",
        "  ",
        "		*   ",
        "	",
        "		kgm3nK_;}  			  else 	  	  { 	 ",
        " ",
        "",
        "	P	  ",
        "	  ",
        "",
        "=	",
        "",
        " 	  ",
        "u8(ly,   		 TmLs7l,",
        "",
        "	 ",
        "	b0CXe) ",
        " 	 ",
        "		< ",
        "",
        "",
        "	Rsv",
        "	   *	  ",
        "	 ",
        "",
        " 	 vElo77wk; 		 ",
        "",
        "",
        " Kfn3Cwdy   	 = 		    PC;	 	  	Kqxx ",
        "		",
        "= 	",
        " ",
        "		",
        "  Si7PpGR 	> 	 	  nAQpU    *     ",
        "ZzKKTw	 * ",
        "	",
        " F1YBX;}		 	  ",
        " u    = ",
        "		",
        " ",
        " b5Y(ElMu 	",
        "	 ",
        "	<",
        " ",
        "",
        "   q);		  	 while",
        "  		",
        " (uaZYTS(PTO3h 	 ",
        "",
        "",
        "	> 		",
        "	",
        "",
        "ScNsC83, 		",
        "  ",
        "HwfCIBS6))		 ",
        "",
        "	{  	",
        " ",
        "u     			=   ",
        " 	",
        " ",
        "A9u",
        " ",
        "	",
        "*	",
        " Uk ",
        "",
        "",
        "	 >	 vekUe ",
        "",
        "* ",
        "  ",
        "  fu5JS2p; 		",
        "",
        "	W4QX5 	 ",
        " =  		  	T_ ",
        " 	<	  ",
        "	 ",
        " v",
        "    ",
        "	",
        "*",
        " ",
        "  sINFTVrY;	 	 	JjuZ	 ",
        "",
        " 	= 	",
        " 	   	v  ",
        " 	+  	   UpG39  ",
        "		",
        "	",
        "+",
        "",
        "",
        "  oef9PN 		 +   ",
        "  ",
        "",
        "sVcS8;",
        "",
        " ",
        "	t 	    ZZ ",
        "",
        "",
        "= 	   	",
        "yQRtDG;F9qEW  	  ",
        "	",
        " = ",
        " ",
        "llOi	",
        " ",
        "	",
        "+",
        "  ",
        "",
        "  f ",
        " ",
        "+		",
        " ",
        "",
        "c",
        "",
        " ",
        "<",
        " ",
        " ",
        "		  	l0kZ;",
        " ",
        "   	}			 w	 ",
        "	   	=    ",
        "",
        "h >",
        "  ",
        "",
        "rJ;}	   if",
        " ",
        "(zOOJ  ",
        "			  +",
        " ",
        "    eTQuelil     ",
        "<",
        "	   ",
        "gU6YTH	 ",
        "",
        " *  	  	 OJwL4)",
        "	",
        " 	 {",
        "    ",
        " 	yhrG3PR   	",
        " ",
        " = ",
        "  ",
        "",
        " dPC;		 	  while	",
        "		  ",
        " (K6bPfr ",
        "   ",
        " > 			",
        "  zj1) 		 	  { 		",
        " nxTOB",
        " ",
        "  =   ",
        "",
        "	 	 ",
        "	vA",
        " ",
        "  * 		_MBA",
        "",
        "	   	*",
        "	 ",
        "",
        "	LJs56N1_P",
        "	",
        " ",
        ">  ",
        "",
        " XT34df;  	  oTdW",
        "   	q5GzY7  	",
        "   =",
        "  ua3T(); ",
        "",
        "  ",
        "S ",
        "		 	  _ioBUjkvx 	 ",
        "	  ",
        "=	   	 ",
        " ",
        "G_0nr1 ",
        "",
        "",
        "	+		  	 uLkarEco_",
        "",
        "   ",
        " + 	 cwz",
        "  		 ",
        "  ",
        "	<",
        "		 	 x; ",
        "  ",
        "  Y0aZT  	 ",
        "",
        "",
        "  = 		",
        "    FGDGPAzd	",
        " ",
        "	",
        "*	  	  ",
        " ",
        "p7FDdXP ",
        "	",
        "",
        "	> 		",
        "   O 			* 	 t0Fh; ",
        "		",
        "	G  ",
        "",
        "  =	 c4yn <",
        " l8S",
        "  ",
        "	* 	  ",
        "_tJrn9(N, 		",
        "m8Kyqs6_);ghh0",
        "		",
        "	 = 	",
        " 	bg5mNiz  ",
        "	 	 +",
        " ",
        "  	s ",
        " + ",
        "    VK;	 	",
        "	",
        "}",
        " ",
        "Y  	  		LQ ",
        " ",
        "",
        "   = 		   VoEIbWkQ ",
        " ",
        "<",
        " 	",
        "	P",
        "     * ",
        "	 ",
        "  tw8fX; 	 		while 	   (jLWvz ",
        "",
        "",
        "		 	+			  JmmHnAuj ",
        " ",
        "		",
        " +	",
        "",
        "  ",
        "d25FgaOr)",
        " ",
        "{  ",
        " 		",
        "	suGyGtKx  ",
        "   = ",
        "",
        "",
        "GlJeUx;zG	 ",
        "",
        "= ",
        " 	  D9vAUrh;",
        "	",
        " 		}",
        "",
        " ",
        "  	 G44O5NfY		 	 DGkJa",
        "",
        " ",
        "	=	    KpE ",
        "    < ",
        "  ",
        "G0aAaI ",
        "",
        " ",
        "*  ",
        "  	",
        "	cZ;     PIH4QWSh ",
        " ",
        "	  RTB3npP6s",
        "",
        "  =",
        "	",
        " 	",
        "KLEXNXYl",
        "   *  	kwS 		 	  + ",
        " O2hoHwk	   	",
        "+  	 		",
        " ",
        " bEssIEuGb;  	 while  	(JV9UOK 		",
        " ",
        "",
        "	+ ",
        " 		 	 xYaVn1USt			",
        "  ",
        "",
        "  + ",
        "	",
        " EBwvRf ",
        " ",
        "		 ",
        "+  zi)",
        "",
        "	 	  ",
        "{  BOHs5d4 ",
        "	  ",
        " 	AduIVP42I  	",
        " =	",
        "	",
        "",
        " WOSi8iG ",
        "	",
        "  ",
        "<     Im2nk   		",
        "",
        "",
        "  	*  ",
        "",
        " ",
        " qb",
        " ",
        " ",
        "*		 wk5XP7QV; ",
        "",
        " ",
        "	 xtfH     e",
        " ",
        "	",
        "		=    N; 	",
        "	 ",
        "",
        "IJwy2rb",
        " 		",
        "=",
        "  ",
        "",
        " _n(WnFO5Xdg)",
        "",
        "",
        " <     j  	",
        "	",
        "	  *			 ",
        "  ",
        " ",
        " C0mEU7sj;	 	  	  T",
        " ",
        "=  ",
        " RWfsKMh 	    < 	    	",
        "yHHSV_ZQ",
        "     ",
        "+",
        "	    	LIDlPFgS  	 ",
        "  		*",
        " ",
        "",
        "  	 fO5ZJfl;		",
        "",
        "  F3aeN1   	 YJ7pb 	=  		 	 zn0jKaLy ",
        "",
        "	>	",
        "	",
        "	",
        "  nNHHx   	 ",
        "	",
        ">",
        " ",
        "eOeLQNr",
        "",
        " 	 +",
        " ",
        "fA;   ",
        "  d5QpWs     ",
        "",
        "=",
        "  ",
        "  sdYrY 	",
        " ",
        " ",
        " 		+ ",
        "",
        " ",
        " 	sZRlHDFh",
        " ",
        " 	 	 	<  	 MX;c ",
        "  ",
        " = vFZQ ",
        "",
        "	+	  	 	M9EidgiXy	 ",
        "",
        " ",
        " 	 >",
        " 	T(n1GTm3_X, ",
        " 	iaC6,	",
        "	 ",
        "	 T0f);",
        "   	 ",
        "}",
        "",
        "    ",
        "GXYxricpS	 	",
        "	=",
        "    fPMzPnR(EkxfKM7Z   	 		>",
        "",
        "",
        " i,   	OV__1OeWl	   ",
        "",
        ">   			Yzo7v1d, 	 ",
        " ",
        "  E);}	 	   else     ",
        "{   ",
        "		if	",
        "  	",
        "   	(Qm4(jvu ",
        "	<",
        "			 ",
        " ",
        "uvD, ",
        " ",
        " ",
        "	  HVF6 <   	Tvaz3oru,	",
        " ",
        "  FcI97ty	   +",
        "  PzGm8j)) 	    ",
        "{	 	 	  ABRQ	",
        "",
        " 	",
        "	aE3y0 ",
        "		= ",
        "wR90scz4  ",
        " ",
        "	 ",
        " + 	 ",
        "",
        "  	fq6v9ACS ",
        "",
        "",
        ">   	  		",
        "ALTJ8SGb;  	",
        "  ",
        "hvtV4MQ0			 =",
        " ",
        "Oj4cLNZP;	 	seasSuy		 ",
        "	UOYYcvk ",
        "   ",
        "=",
        "  ",
        "		 Oh3(mwod5vA, 		E)	 	  	",
        "  >	     	b_6m0mrW();",
        "  	 ",
        "		 iP 	  	 = 			C2LxP_5; ",
        "	    ",
        "",
        "HUbTh",
        "  	",
        "K9gLlzp6  	 =		",
        "",
        "  	eWiysBb; 		",
        " ",
        "	 ",
        "k ",
        "    Y8IK",
        " ",
        "=	 	 ",
        " 	PYlAswz  	",
        "",
        " 		 <	  ",
        " 	",
        "	dZI6	",
        "",
        "   	",
        "	 +	 	ETWfG(YvUE, 			 L,",
        "	 ",
        "",
        "hayBN);}  ",
        " 	 for",
        "	 (eePuxmAr		",
        "	 =   	 	 cn1md_U9",
        "	  >",
        " hDSgJ4TE",
        "",
        "  <	 	 	CUf_eLzbi;  ",
        "",
        "  ",
        "tN(zB)  ",
        "	",
        "	",
        "	* 	   dadefW9",
        "		",
        "",
        " 	> 		",
        "  	eD; 	",
        "	 oue ",
        "  	=",
        " 	",
        " ",
        "QA     <",
        "   ",
        "  	e",
        "   ",
        "",
        ">	",
        "",
        " ",
        "yhA",
        "	  +	   ",
        " 	",
        "",
        "cSCR8XleE)	 ",
        "",
        "	 ",
        "	 {	 ",
        "  E6h 		  ",
        " ",
        " Tnh5mM7e1  = ",
        " fnSN",
        "",
        "",
        "   <	",
        "  	",
        "",
        "   W5	 	>	",
        "",
        "",
        " R",
        "",
        "	 <    ",
        "AcsjeQ1wg;	",
        "	",
        " ",
        "	GDZ",
        " ",
        "",
        "	  YyfcuLg 	 	  	 = 	",
        "	 ",
        " WKnQ(aPD,",
        " 	WwLK,  ",
        "	",
        " ",
        "	 EBz338LD)  ",
        "  *	 		YZkd0jA",
        " ",
        "",
        "	+ 		   ",
        " ",
        "x6lzUgG;}} 	    qIEli3     =",
        " ",
        "	zPEv(m14UL, 			 grAnVA1s  		",
        "<		 	RpWO,		",
        " gJZUKlhsH    <	  ",
        " JoX);",
        "",
        "",
        " while",
        "",
        "  	(lYjEEiR9T(mtgKT",
        "",
        "",
        "    	 < ",
        "",
        "",
        "R1a))	 		{ 	",
        " 	  	Y2	",
        " 	  ",
        "	",
        "=	  ",
        "		jw   ",
        " 	",
        "> ",
        "		 ",
        "	 eU6q 	",
        "		 ",
        ">  	",
        " kV();	 	 FQ70 		rIS    	",
        " =   ",
        "",
        " uDYbR1Ee(dWiwuLd1c,",
        "	",
        "	",
        "	 GW,	 ",
        "",
        "		 ",
        " hQHLi7)  <",
        "    	",
        " vP			  ",
        "",
        "",
        ">		 	",
        "W_O_vNwB;L71 	    	= 	   O3	   	",
        "	  ",
        "<  	   ",
        "zVoWq",
        "	 	 	>",
        " 	jnSKq2hN;",
        "   ",
        "",
        "	  }",
        " 	",
        "",
        "z980hpNQ ",
        " ",
        " pYBi0	",
        "  		=",
        "   	 	 	bJEo0J",
        " 	 	 	 <	 	",
        "	_r   	 ",
        "* 		 ",
        "",
        "W2owH();",
        "	 ",
        "	 	while		    (mJ)",
        "",
        " ",
        " {		",
        "	 NoGXeT",
        "",
        "  =	 	  N 	    	+",
        " 	 ",
        "  ",
        " DEkP9gd",
        "	 		+",
        "	   	 	Yo",
        " ",
        "",
        "	 	  	>  	 ",
        "v2IcnR;	   	Ggdwx	",
        " ",
        " 		 Ha2zlTt    = ",
        " ",
        "HWOoTP",
        "",
        " ",
        " <",
        "",
        " ",
        " wubAh  	",
        "  	 > 		",
        "v  		 <	",
        "",
        " ",
        "    	e54Uw;k3r",
        "",
        "  ",
        "=	  	  Q_SB	 ",
        "  	*	",
        " ",
        "PAqODsksF ",
        "",
        "    <",
        "",
        "",
        "  uKY6JWq9	 <	 ",
        "",
        "",
        "  I;",
        " }	 ",
        "rTKRCe1G8 ",
        "			   = ",
        "    ",
        "buxTB 		  ",
        " < ",
        "	",
        "  Tzft	 ",
        " 	",
        "   	* 	 	 ",
        "",
        "",
        " 	AqS",
        "	",
        " 		 *	 ",
        "	  iE40CiLkc;}}"
      ],
      matches: [
        [
          [5, 6],
          [64, 65, 66, 67, 68]
        ],
        [[29], [366]],
        [[16], [179, 180, 181, 182]],
        [[4], [55, 56, 57, 58]],
        [[4], [42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55]],
        [[21], [218, 219, 220]],
        [[24], [269, 270, 271, 272]],
        [[23], [246]],
        [[26], [286]],
        [[30], [371, 372, 373, 374, 375, 376]],
        [
          [9, 10, 11, 12, 13],
          [144, 145, 146, 147, 148, 149, 150, 151, 152, 153]
        ],
        [[19], [210]],
        [[23], [251]],
        [[9], [100, 101, 102, 103, 104, 105]],
        [
          [16],
          [178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190]
        ],
        [[29], [359]],
        [[9], [96, 97, 98, 99, 100, 101, 102, 103, 104, 105]],
        [
          [15],
          [
            147,
            148,
            149,
            150,
            151,
            152,
            153,
            154,
            155,
            156,
            157,
            158,
            159,
            160,
            161,
            162,
            163,
            164,
            165,
            166,
            167,
            168
          ]
        ],
        [[16], [192]],
        [[24], [253, 254, 255, 256, 257, 258, 259]],
        [
          [28],
          [
            316,
            317,
            318,
            319,
            320,
            321,
            322,
            323,
            324,
            325,
            326,
            327,
            328,
            329,
            330,
            331,
            332,
            333,
            334
          ]
        ],
        [[23], [222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233]],
        [[12], [144, 145, 146]],
        [[19], [200, 201, 202, 203, 204, 205, 206, 207, 208]],
        [[23], [235]],
        [[2], [36, 37]],
        [[15], [179]],
        [[23], [253, 254, 255, 256, 257, 258, 259]],
        [[24], [278, 279, 280, 281, 282, 283]],
        [[8], [90]],
        [[19], [208, 209, 210]],
        [[26], [294, 295, 296]],
        [[3], [45, 46, 47]],
        [[5], [64, 65, 66, 67, 68]],
        [[18], [202, 203, 204, 205, 206, 207, 208]],
        [[7], [82]],
        [
          [6, 7],
          [
            42,
            43,
            44,
            45,
            46,
            47,
            48,
            49,
            50,
            51,
            52,
            53,
            54,
            55,
            56,
            57,
            58,
            59,
            60,
            61,
            62,
            63,
            64,
            65,
            66,
            67,
            68,
            69,
            70,
            71,
            72
          ]
        ],
        [
          [24],
          [
            251,
            252,
            253,
            254,
            255,
            256,
            257,
            258,
            259,
            260,
            261,
            262,
            263,
            264,
            265,
            266
          ]
        ],
        [[3], [218]],
        [[23], [248, 249, 250, 251]],
        [[5], [68]],
        [
          [17, 18],
          [202, 203, 204, 205]
        ],
        [[29], [350, 351, 352, 353, 354, 355]],
        [[23], [251, 252]],
        [[31], [376, 377, 378]],
        [[15, 16], [180]],
        [[8], [88]],
        [[23], [252]],
        [[5], [55, 56, 57, 58, 59, 60, 61, 62, 63]],
        [
          [4, 5],
          [58, 59, 60]
        ],
        [
          [29],
          [
            266,
            267,
            268,
            269,
            270,
            271,
            272,
            273,
            274,
            275,
            276,
            277,
            278,
            279,
            280,
            281,
            282,
            283,
            284,
            285,
            286,
            287,
            288,
            289,
            290,
            291,
            292,
            293,
            294,
            295,
            296,
            297,
            298,
            299,
            300,
            301,
            302,
            303,
            304,
            305,
            306,
            307,
            308,
            309,
            310,
            311,
            312,
            313,
            314,
            315,
            316,
            317,
            318,
            319,
            320,
            321,
            322,
            323,
            324,
            325,
            326,
            327,
            328,
            329,
            330,
            331,
            332,
            333,
            334,
            335,
            336,
            337,
            338,
            339,
            340,
            341,
            342,
            343,
            344,
            345,
            346,
            347,
            348,
            349
          ]
        ],
        [[29], [350, 351, 352, 353, 354, 355, 356, 357, 358, 359]],
        [[2], [40]],
        [[23], [216, 217, 218, 219, 220]],
        [[16], [199]],
        [[15], [168]],
        [
          [16, 17],
          [199, 200]
        ],
        [[18], [208]],
        [[26], [288, 289, 290, 291, 292, 293, 294]],
        [[23], [252, 253]],
        [
          [27],
          [303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315]
        ],
        [[7], [77]],
        [[22], [231, 232, 233]],
        [
          [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
          [200, 201, 202, 203, 204, 205, 206, 207, 208]
        ],
        [[12], [142]],
        [
          [7, 8],
          [77, 78, 79, 80, 81, 82, 83, 84, 85]
        ],
        [
          [26, 27],
          [298, 299, 300, 301, 302, 303, 304]
        ],
        [[17], [190]],
        [
          [9],
          [
            91,
            92,
            93,
            94,
            95,
            96,
            97,
            98,
            99,
            100,
            101,
            102,
            103,
            104,
            105,
            106
          ]
        ],
        [[29], [362]],
        [[22], [231]],
        [[2], [38, 39, 40]],
        [
          [15],
          [165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178]
        ],
        [
          [28, 29],
          [344, 345, 346, 347, 348, 349]
        ],
        [[15], [171]],
        [[27], [312, 313, 314, 315]],
        [[16], [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]],
        [[24], [278]],
        [[11], [132, 133, 134, 135]],
        [
          [29],
          [337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349]
        ],
        [[12], [132, 133, 134, 135, 136, 137, 138, 139, 140]],
        [[14], [163]],
        [[16], [182]],
        [[5], [64]],
        [[19], [214]],
        [
          [24],
          [252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264]
        ],
        [[24], [259]],
        [[3], [42, 43, 44]],
        [[25], [286]],
        [[15], [176]],
        [[14], [162]],
        [[23], [240]],
        [[27], [306, 307, 308, 309, 310]],
        [[21], [218]],
        [[5], [58, 59, 60, 61, 62, 63]],
        [[27], [301]],
        [[3], [42]],
        [[2], [36]],
        [
          [9, 10],
          [109, 110, 111, 112, 113, 114, 115]
        ],
        [[15], [168, 169, 170, 171, 172, 173]],
        [
          [19],
          [
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44,
            45,
            46,
            47,
            48,
            49,
            50,
            51,
            52,
            53,
            54,
            55,
            56,
            57,
            58,
            59,
            60,
            61,
            62,
            63,
            64,
            65,
            66,
            67,
            68,
            69,
            70,
            71,
            72,
            73,
            74,
            75,
            76,
            77,
            78,
            79,
            80,
            81,
            82,
            83,
            84,
            85,
            86,
            87,
            88,
            89,
            90,
            91,
            92,
            93,
            94,
            95,
            96,
            97,
            98,
            99,
            100,
            101,
            102,
            103,
            104,
            105,
            106,
            107,
            108,
            109,
            110,
            111,
            112,
            113,
            114,
            115,
            116,
            117,
            118,
            119,
            120,
            121,
            122,
            123,
            124,
            125,
            126,
            127,
            128,
            129,
            130,
            131,
            132,
            133,
            134,
            135,
            136,
            137,
            138,
            139,
            140,
            141,
            142,
            143,
            144,
            145,
            146,
            147,
            148,
            149,
            150,
            151,
            152,
            153,
            154,
            155,
            156,
            157,
            158,
            159,
            160,
            161,
            162,
            163,
            164,
            165,
            166,
            167,
            168,
            169,
            170,
            171,
            172,
            173,
            174,
            175,
            176,
            177,
            178,
            179,
            180,
            181,
            182,
            183,
            184,
            185,
            186,
            187,
            188,
            189,
            190,
            191,
            192,
            193,
            194,
            195,
            196,
            197,
            198,
            199,
            200,
            201,
            202,
            203,
            204,
            205,
            206,
            207,
            208,
            209,
            210,
            211,
            212,
            213
          ]
        ],
        [[29], [365]],
        [[7], [79]],
        [[24], [272]],
        [[28], [324]],
        [
          [14, 15],
          [162, 163, 164]
        ],
        [[28], [343]],
        [[10], [106]],
        [
          [22, 23, 24, 25, 26],
          [288, 289, 290]
        ],
        [[24], [269]],
        [
          [21, 22],
          [218, 219, 220, 221, 222]
        ],
        [[16], [180]],
        [
          [10, 11],
          [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44,
            45,
            46,
            47,
            48,
            49,
            50,
            51,
            52,
            53,
            54,
            55,
            56,
            57,
            58,
            59,
            60,
            61,
            62,
            63,
            64,
            65,
            66,
            67,
            68,
            69,
            70,
            71,
            72,
            73,
            74,
            75,
            76,
            77,
            78,
            79,
            80,
            81,
            82,
            83,
            84,
            85,
            86,
            87,
            88,
            89,
            90,
            91,
            92,
            93,
            94,
            95,
            96,
            97,
            98,
            99,
            100,
            101,
            102,
            103,
            104,
            105,
            106,
            107,
            108,
            109,
            110,
            111,
            112,
            113,
            114,
            115,
            116,
            117,
            118,
            119,
            120,
            121,
            122,
            123,
            124,
            125,
            126,
            127,
            128,
            129,
            130
          ]
        ],
        [[22], [224, 225, 226, 227, 228, 229, 230, 231]],
        [[7], [74]],
        [
          [23],
          [
            235,
            236,
            237,
            238,
            239,
            240,
            241,
            242,
            243,
            244,
            245,
            246,
            247,
            248,
            249,
            250,
            251
          ]
        ],
        [
          [28],
          [321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334]
        ],
        [[17], [200]],
        [[3], [47, 48, 49]],
        [[11], [137, 138, 139, 140]],
        [
          [29, 30],
          [359, 360, 361, 362, 363, 364, 365, 366, 367, 368]
        ],
        [[10], [119]],
        [
          [26, 27, 28],
          [
            298,
            299,
            300,
            301,
            302,
            303,
            304,
            305,
            306,
            307,
            308,
            309,
            310,
            311,
            312,
            313,
            314,
            315,
            316,
            317,
            318,
            319,
            320,
            321,
            322,
            323,
            324
          ]
        ],
        [
          [29],
          [
            266,
            267,
            268,
            269,
            270,
            271,
            272,
            273,
            274,
            275,
            276,
            277,
            278,
            279,
            280,
            281,
            282,
            283,
            284,
            285,
            286,
            287,
            288,
            289,
            290,
            291,
            292,
            293,
            294,
            295,
            296,
            297,
            298,
            299,
            300,
            301,
            302,
            303,
            304,
            305,
            306,
            307,
            308,
            309,
            310,
            311,
            312,
            313,
            314,
            315,
            316,
            317,
            318,
            319,
            320,
            321,
            322,
            323,
            324,
            325,
            326,
            327,
            328,
            329,
            330,
            331,
            332,
            333,
            334,
            335,
            336,
            337,
            338,
            339,
            340,
            341,
            342,
            343,
            344,
            345,
            346,
            347,
            348,
            349,
            350
          ]
        ],
        [[29], [355]],
        [
          [17],
          [187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200]
        ],
        [[7], [77, 78, 79, 80, 81, 82, 83]],
        [
          [10],
          [106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]
        ],
        [[24], [272, 273, 274, 275]],
        [[30], [376]],
        [[27], [303, 304, 305, 306, 307, 308, 309, 310]],
        [
          [17],
          [
            130,
            131,
            132,
            133,
            134,
            135,
            136,
            137,
            138,
            139,
            140,
            141,
            142,
            143,
            144,
            145,
            146,
            147,
            148,
            149,
            150,
            151,
            152,
            153,
            154,
            155,
            156,
            157,
            158,
            159,
            160,
            161,
            162,
            163,
            164,
            165,
            166,
            167,
            168,
            169,
            170,
            171,
            172,
            173,
            174,
            175,
            176,
            177,
            178,
            179,
            180,
            181,
            182,
            183,
            184,
            185,
            186,
            187,
            188,
            189,
            190,
            191,
            192,
            193,
            194,
            195,
            196,
            197,
            198,
            199,
            200,
            201,
            202
          ]
        ],
        [[11], [132]],
        [[2], [27, 28, 29, 30, 31, 32, 33, 34, 35, 36]],
        [[28], [327, 328]],
        [
          [3, 4],
          [45, 46, 47, 48, 49, 50, 51, 52, 53]
        ],
        [[7], [84]],
        [[19], [216, 217, 218]],
        [[8], [86, 87, 88, 89, 90, 91]],
        [[23], [242, 243, 244]],
        [[16], [179, 180, 181, 182, 183, 184, 185]],
        [
          [13, 14],
          [156, 157, 158, 159]
        ],
        [[16], [185]],
        [[10], [122, 123, 124, 125, 126, 127, 128, 129]],
        [[15], [165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176]],
        [
          [28],
          [
            316,
            317,
            318,
            319,
            320,
            321,
            322,
            323,
            324,
            325,
            326,
            327,
            328,
            329,
            330,
            331,
            332,
            333,
            334,
            335,
            336,
            337,
            338,
            339,
            340
          ]
        ],
        [[28], [343, 344]],
        [[22], [223, 224]],
        [
          [4, 5, 6, 7, 8, 9],
          [92, 93, 94, 95, 96, 97, 98, 99, 100]
        ],
        [[24], [253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264]],
        [[8], [72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85]],
        [[8], [72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86]]
      ]
    },
    {
      name: "Results #3",
      slug: "result-3",
      score: 0.056543837357052,
      fileOneName: "001.java",
      fileTwoName: "002.java",
      fileOneMatches: [2, 3, 4, 5, 6, 7],
      fileTwoMatches: [
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31
      ],
      fileOneLines: [
        "public class ERCJb {",
        "private q1INlWzHq i(lbL4 h8xdE8h9, qxnOLy6W U, pTf5EDo phA, Q WkUxk_gEu) {",
        "for (NdQ = cp0Dmy + A * UTck * IG2; oao_w1Ri * kS_b8MoFn < M * W9SnB5P; O4 = SyARKYrM < Fncov) {",
        "if (bTJy0GPO * rAFiA > l1yTboN) {",
        "JSYRvvDwK I = jnb + _Q < iOSn();",
        "wlJ VDL0 = MeAO9qK < oO + A8M * czWof5AfJ;",
        "Z6I2 = MB > A(iK9Qd);}",
        "m = eZ;",
        "if (XFnhUkIC(g + L8W8ck, _nr7mOr + yw8DE, ESh + YRnojwjN)) {",
        "fo_Us q = PoexXgeL < D * OcRs0o(Xbic2bFGx, z, j9RH);",
        "a1 _Z5 = tQfOEH > az > _AbRQq < CVivz;}",
        "else {",
        "qFz2 UiyktDcUR = vqglV * F + PH(Hv, Opx7S3DN2, y3zBVn);",
        "fz5o = BF + ofE5wtFUN + T0VU;",
        "nR GxTIp2 = YWLMLJ(MUc * uLtaUK);",
        "u1p4YoJK = hQq < uC * R1yr8NFR(pMwVy8, WghqEbhH6, UlNPXDhz);",
        "Td1S a = TsBKg86 * J < QMt();",
        "F = J > vC > uxjyEbTtI > SKlD;}",
        "for (YeY4X_G VkfM = UWEg > x * F; q0ZscHCj; mYCi = UID6e0SH3 + W6v > z + EqHDcbLhY) {",
        "S sIoltBh = EB2w();",
        "XbfBez4X co6KJ = BhJgi5zK;}",
        "for (Zp jLJA = Zk7 > R4Q0tK4xE; S6GCb0Zt2; AbyCT = Su < qnhsAYN + r) {",
        "LDauk = h > cWQw7xjb < jgBEifa1(vfsnsL0jz);",
        "wA s = lJRD;",
        "Q46Q2OT = nVmH2uep(JsA * uB5X);",
        "GcUg1kza FJOw = KgAsR(QfIqw6CZ, IufRGU, ic) + jBGqJa9 > h8DiH;}}",
        "K1Q0 = _(bubC > TYSmec);",
        "taqhLQ4j = e6KAzQ9x < hBBX < eo + Y;",
        "haazvSXo = D3S > QDlK * nMC;}}"
      ],
      fileTwoLines: [
        "public class fOr54jzw {",
        "private XhX o(phy Li2, RUzR EGE1, HtNtb bxHZ3s8, RFWodpN0O F9H, p cznoGBrW) {",
        "if (CEhFo + g * dOYzBzX) {",
        "if (HgYNkFm < al5HPnc > T8Qb35) {",
        "gGV = B9omveUTf(jzz, LG7I6pHs, seactT58) + o < oKRiTOGYX;",
        "oJd_30yhs = cY;",
        "Q4O3uZ = FJ5ci_fF * _ * Zf_KF(gT4_gCfzB);",
        "jei5b = h * aqbl7gcaq + yikUA * NgUEYWG;}",
        "if (bAuW > oYXt(U, Bg)) {",
        "KWD = tUpY2VJ(hIpu < J, JLNcLxR0);",
        "Sb8FDgDT = GOh < ou65L7z + DS;",
        "mH djSjX4l = RD();}",
        "else {",
        "z = rvnCL + Rz03A;",
        "wRULGaD7N pfHRfQ7ak = T3cxhTqM(S_u4OXu6s, WFdHh6GDC) * pIMmDDx(XWATW, uQZnkL, q73Kq2roR);",
        "r6jP2 W7ihd1Q = fFCmZib7x + Vdfd < oB + CItMR;",
        "S gyijSwfh = DhNH + S * tTz2VSfm;",
        "D7yZPBMZ Ojo = PrnV;}",
        "iwaI9afuZ = kTnkLQajL(JDVxoQ) + tAMNYS(oPDFLpi, JhJng2K, nX_O8);}",
        "else {",
        "BzeJ3CA6m Awtd = Et;",
        "while (E6tm7gM8 * g0iHfmY > tDm(U)) {",
        "MI = PS * q + c(tf3DCb, vpMapvmcN);",
        "ugye_cm = jWvXErd5s + kdFrZ * JKBkvM(k7, P741B1S);VV81Z0YaJ = d > HRbcD0 * A;",
        "}",
        "if (bxbfvtpAT * EI365RYQ * EwP) {",
        "oXPaHR = PJ(N, SUm, SFrrk7V) > nP * cdz;}",
        "for (RTw0sDb2 = vnF; CPm9Akr > FTrtNA5 < hnx; v9gVbEtk = m3TdCn7O) {",
        "cUxx = PAvsvn(OpK(), PV < N, Q4C(grwlEWF));",
        "sZBIo8bn = Z < bMU4X;",
        "H7NuCgkf tsLhRz5A = ijN4uzxs * GU5 < A + NXVyHk1;}}",
        "n0 RzB = WH;",
        "Q W = iNofadFFZ < lbA6eC < xsRHKN1B;",
        "while (k64H * XHzqrMA2 + WTx + Pe) {",
        "if (_gfXR8a36 * sfZ < Krr + OTzL5) {",
        "f2ck = XrOjygc + P * uY > VW2c6;",
        "U = VjcsCkMo0 + LJLTwOsk < s5nH1 < kkJmKO;}",
        "else {",
        "YLKyK0nn sRX_v = lqZ72v + yD1jsLyP < MIh_;",
        "v7sn3k8 = IZ0jU < Nsr + Yz_Bnwte;",
        "NbvROpp XmFDyb5C4 = wNuCgd + v8z4F5MYL > lkRu6dQFg + XY;",
        "Wpyn = CyZ9V;",
        "FEbV Xfs46F1o = TQp_ > lD6vwv > brLc7h;",
        "T8S gqQ = G1dW * hGX9Rw6T + Xh1xAOJxh * tXTTW5vT;}",
        "ra_R YZf8Z = vRMD + wJrYQLq1 < BusXKa * Y;",
        "for (ueKj0 = uDg5x3M < edo > xGeQsaJ; p(Dxjsd + TmDJ, M7tNwdbU * lLD6n); OI9Y4sb = jlKCZ < J5_rrMR + kR4Ej9x) {",
        "fd_BrVN = QoWXC2;",
        "uYEYVd = W9JBG;",
        "PiBGK = k048DO * vRRh0Q + u;",
        "tpSfc1xK geJJd = tLVCVu6Zu;}",
        "RR32m JuTFi7_BA = INuXEOKKH < zdbQ * Dw;",
        "for (I8i7u objfF = V(gddnfzS(), BDfT + pH7y3XhU, gVMKkf); ypJD > ICoKh * Bjfuql + kR8g; BF = KLIfLbf > NL92y + t > A4Y5Av_1) {",
        "Z_TAkLAy DqmA = FzCa;",
        "nr = kZ8JLN() * m * HfySS;",
        "xkpb = Zjh1 > SAb * SyRm7KXFZ;",
        "sN adLqS = InxG9d > P > Vy1rD7S < W1ORjKiSG;",
        "R1sFn5Ri YDTuzW = MBGYMENu * oRnoppqU > x_DNVCc9 > UzyVfrQ4;}oVPg2UJ = qutYWj9Q;",
        "}",
        "RO = E4jE > jZXNMga * dtSh1B * lGTpkf;",
        "while (j9 < W0J < y()) {",
        "O6DlCXd = Q;",
        "while (jvKxyn) {",
        "YB kl = fUbG(zUse, fLrmsPi < y);eVHa7Hf = o > y_ > QXzep2cL * L;",
        "}",
        "if (_Clb4m0 * r7xIzLXeN * cGADKK()) {",
        "m bdq = kG6AfOZ;",
        "pW = Tyq < wf + _G < A;",
        "IKIzcBJ = wEmLdBn(sh) * DzFndPF < KyBu;",
        "GhOjY4 = v * szwu + UfKvMtDSx;",
        "mvBjfx uUY = M12eK(F1eflUI, JyYsWf) + vW > nfTV;}kH = G();",
        "}",
        "nWG = p5 > UNWNVf7S < g3KXmqPv < up5lT;",
        "while (I(YBwFbTKL * aK, EX98 + LRDLX)) {",
        "KJ = kGCPg * MEPhx2GE + WXi0N;",
        "while (pMDpvYL < lMaqG1W + wJxl(xy52ugZZr, HNr6fm5, YhjpW)) {",
        "nj egFjZJG1W = xLcPW > Ka7Lh9j < p1o1 < UN;",
        "U7q y95T7l = INUjgI;t = z * oS2SZazy + yEpKiJ8 > c;",
        "}",
        "for (U = hlz9F(Jbt + JzzHupV, qF9oWv + ay5Jnk2, sJ * a); OufT8; b3 = p0WJeS > BUjWGCY5 + oZu) {",
        "G1R4 = ioiHPFp5s() > QrjxtW < qFwpE;",
        "JFz HwH8bG6XK = iJcAS073 + cx4qpL > lpZ54 + R;}IBsMgRQF = BxJ > _cu6 + G853Zi_(Wur0);",
        "}",
        "X3gzlf_ = ZNKwc3I;",
        "while (zC) {",
        "for (H = JeSn(x7 > V); FveIb(aU < Igl7, IU9); G57z = zCvF > sqgG + O + aboEEYcXW) {",
        "LDN = mX * Q < OeM2L * zx;",
        "_ = CAEdl9IFy + cpXd + t + IG;",
        "r = pZ * TL > nux;}",
        "if (sZf7()) {",
        "J2 BPWpRZ = ZIZy6Op3(gFXq6Jg(Z), YWXbmdj + tKBYE);",
        "Kg = nuo + lJHAYYI + xvrUyTU * JCkWB;",
        "O = K__3z * H0U3LBx < _uv();}",
        "else {",
        "OtwkdYPH = pI5uW_Fco;",
        "NlkKdV = v * M8xONnGW > SUR2ob(mtdxvaih, FnNDNWM, RJ);}",
        "jZRhhZdc = MdRbbo9D < B9;B = Yv * jWyzDxtVX + fohk73Wp > HW9;",
        "}",
        "Y tI = gtbLJ(N6My, _bXtq91) > Q4m + Q7ZFSZMJ;",
        "if (XGSc5WYjF * _2nPws6q_ > yfQVYmy + FCUqwp) {",
        "for (BJ5g2fpx = WKDavyUTd; N < HqBWChD; xAAgFUR3 = H + K9BflLMB + RzVNzj59) {",
        "yrd mYH7 = oq8t40Hn1();",
        "U651CHGWl = DMVI * TbjfbxU < vfPKphw_ * IIraADb;",
        "tRsh x40fbzTF = eziN > mHDF + ID6RzIE + pnt;",
        "D3 = XhF(BCQ2, MVMJSKL) * Ix1v > aGp3aYy;}",
        "for (Lg2P6i dlaOC0CB = InFvS + OGQE + g * Q; i + n14VfM + NZtlIwN + t8qe; r = zS(LQ7ak, zpZWZpC, ZBxj) < q + _) {",
        "m m = qtjgA4kN * SLOXNXhX * rvfvm > GJMMxT8;",
        "c0 EyI2O513 = ZE;",
        "MXmYY = J3 * ePZ + _0U_ > LTOEslr;",
        "VwstT = MUS1GBA42 > MbA0 + VBbcH;",
        "wn_uHsXW zMv = ftI1 + q06gW3 < ScAJ < NZ9m74;}",
        "for (T2jLtmxGq txirYZZx = VNp * H31am4iFF > uy; t + YwRfQ + SNB_BdCTC; mUPzJahN = gGkwv2B) {",
        "D = Yc;}}",
        "else {",
        "wIFNSu = Siie4xPO > PqVdTeT < _v;",
        "while (XWjq < Yvm75BpXy * Q4O8D(L1ng166j)) {",
        "uf W5NaxZH = ckYENWhO + r9ZM7 * S3Ssa(FkCl5YV, L, Xm);",
        "r06YW2uv wEX2MdOI = H > llbeHrdzC < LkuZnM8 > j;Z_k1V = X + RXS < aN > LeLNuSoaa;",
        "}",
        "if (OwoM5u(hnVJ_cM > FILimvCY, Qz > ae9H0hL, kGDDM + oDU)) {",
        "jntXO DJQjrCd = ScwkDGnaM < fBMWu + Km;",
        "r0s0F9GfM = xR;",
        "EkRWr = cxi1;",
        "PetqL OozT6n = B;",
        "pRw iq = aTyS4zO2f(rPPQZ4iK, CDUhE, JoAPVSz) + a4K4 > qb;}}",
        "for (ganDjwqVH = xz8(L_1, ZrNmt55 > e4Se, F > atySuS4L); mgY(zT > pV_sv); ekJMt = VvOxT2vv < oI3Udq > L) {",
        "Erwp44U vBzE8grs = noV5cHexy < UvS4b > q(NrLkSBj, L, wDed);}",
        "for (kB FPdnDW1 = wjH4() * F4eCE > Xq_SdNZ; mbL; R2 = zfAoBE > Ut67VSLVa > Vgjlr * p) {",
        "T = JSxt4Qsm3 < FMwcj + anravN + LjIqKil;}}}"
      ],
      matches: [
        [[3], [9, 10, 11, 12, 13, 14]],
        [[4], [15]],
        [[6], [16]],
        [[3], [11]],
        [[2], [10]],
        [[3], [12]],
        [[5], [16]],
        [[2, 3], [10]],
        [[5], [15, 16]],
        [[3], [14, 15]],
        [[4, 5], [15]],
        [[3], [11, 12]],
        [[5], [15]],
        [[3], [14]]
      ]
    },
    {
      name: "Results #4",
      slug: "result-4",
      score: 1.0,
      fileOneName: "test.java",
      fileTwoName: "test-p.java",
      fileOneMatches: [29, 30, 31, 32, 33, 34],
      fileTwoMatches: [19, 20, 21, 22, 23, 24],
      fileOneLines: ["// Java program for implementation of Bubble Sort ",
      "class BubbleSort ",
      "{",
      "    // Driver method to test above",
      "    public static void main(String args[])",
      "    {",
      "        BubbleSort ob = new BubbleSort();",
      "        int arr[] = {90, 11, 22, 12, 25, 34, 64};",
      "        ob.bS(arr);",
      "        System.out.println('Sorted array');",
      "        ob.printA(arr);",
      "    }",
      "",
      "    void bS(int arr[])",
      "	{ ",
      "		int arrayLength = arr.length;",
      "		for (int j = 0; j < n-1; j++)",
      "			for (int j = 0; j < n-j-1; j++)",
      "				if (arr[j] > arr[j+1]) ",
      "				{ ",
      "					// swap arr[j+1] and arr[j] ",
      "					int swap = arr[j];",
      "					arr[j] = arr[j+1]; ",
      "					arr[j+1] = swap;",
      "				} ",
      "	} ",
      "",
      "	/* Prints the array */",
      "	void printA(int arr[])",
      "	{ ",
      "		int n = arr.length; ",
      "		for (int i=0; i<n; ++i) ",
      "			System.out.print(arr[i] + ' '); ",
      "		System.out.println(); ",
      "	}",
      "} ",
      "/* This code is contributed by Edward Olmos */",
      "",
      ],
      fileTwoLines: [
        "// Java program for implementation of Bubble Sort ",
        "class BubbleSort ",
        "{ ",
        "	void bubbleSort(int arr[]) ",
        "	{ ",
        "		int n = arr.length; ",
        "		for (int i = 0; i < n-1; i++) ",
        "			for (int j = 0; j < n-i-1; j++) ",
        "				if (arr[j] > arr[j+1]) ",
        "				{ ",
        "					// swap arr[j+1] and arr[j] ",
        "					int temp = arr[j]; ",
        "					arr[j] = arr[j+1]; ",
        "					arr[j+1] = temp; ",
        "				} ",
        "	} ",
        "",
        "	/* Prints the array */",
        "	void printArray(int arr[]) ",
        "	{ ",
        "		int n = arr.length; ",
        "		for (int i=0; i<n; ++i) ",
        "			System.out.print(arr[i] + ' ''); ",
        "		System.out.println(); ",
        "	} ",
        "",
        "	// Driver method to test above ",
        "	public static void main(String args[]) ",
        "	{ ",
        "		BubbleSort ob = new BubbleSort(); ",
        "		int arr[] = {64, 34, 25, 12, 22, 11, 90}; ",
        "		ob.bubbleSort(arr); ",
        "		System.out.println('Sorted array'); ",
        "		ob.printArray(arr); ",
        "	} ",
        "} ",
        "/* This code is contributed by Rajat Mishra */"
      ],
      matches: [
        [[29,34], [19,24]],
        [[29, 30, 31, 32, 33, 34], [19, 20, 21, 22, 23, 24]],
      ]
    }
  ]
};
